<?php

$title = 'Add new dish';

$this ->headTitle($title);
?>

<h1><?= $this->escapeHtml($title)?></h1>

<?php

$form->setAttribute('action',$this->url('datagrid',['action'=>'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<!-- Dish name -->
<div class="form-group">
    <?= $this->formHidden($form->get('id')) ?>
</div>

<div class="form-group">
    <?= $this->formRow($form->get('dish_name')) ?>
</div>
<div class="form-group">
    <?= $this->formRow($form->get('category')) ?>
</div>
<div class="form-group">
    <?= $this->formRow($form->get('description')) ?>
</div>
<div class="form-group">
    <?= $this->formRow($form->get('image_src')) ?>
</div>
<div class="form-group">
    <?= $this->formRow($form->get('price')) ?>
</div>
<div class="form-group">
    <?= $this->formRow($form->get('options')) ?>
</div>
<div class="form-group">
    <?= $this->formSubmit($form->get('submit')) ?>
</div>
<?= $this->form()->closeTag()?>


