<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete dish';
$url   = $this->url('datagrid', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete the next item?<br><br>
    <b>Dish name:</b> "<?= $this->escapeHtml($dish->dish_name) ?>" <br>
    <b>Category:</b> "<?= $this->escapeHtml($dish->category) ?>" <br>
    <b>Description:</b> "<?= $this->escapeHtml($dish->description) ?>" <br>
    <b>Image Source:</b> "<?= $this->escapeHtml($dish->imageSrc) ?>"<br>
    <b>Price:</b> "<?= $this->escapeHtml($dish->price) ?>$" <br>
    <b>Options:</b> "<?= $this->escapeHtml($dish->options) ?>" <br>
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $dish->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>