
<?php

use DataGrid\Forms\IndexForm;

$title = 'Dishes';
$this->headTitle($title);
?>
<h1 xmlns="http://www.w3.org/1999/html"><?= $this->escapeHtml($title) ?></h1>
<table><tr><td valign="top">
<?php
$form->setName('filter');
$oMultiCheckboxViewHelper = new \Zend\Form\View\Helper\FormMultiCheckbox();
$oMultiCheckboxViewHelper->setSeparator('<br>');
$form->addElement('category','category','Categories',['1'=>'1','2'=>'2','3'=>'3','4'=>'4','5'=>'5']);
$form->get('dish_name')->setOptions(['label'=>'By Name']);
$form->get('dish_name')->setAttribute('placeholder', 'Example: wine');
$form->get('price')->setOptions(['label'=>'By Price']);
$form->get('price')->setAttribute('placeholder', '0.00 - 9.99');
$form->get('submit')->setValue('Filter');
$form->setAttribute('action',$this->url('datagrid',['action'=>'index']));
$form->prepare();
?>

<?= $this->form()->openTag($form)?>
            <div class="form-group" >
                <span><b>Categories:<b></span><br>
                <?= $oMultiCheckboxViewHelper->render($form->get('category')); ?>
            </div><br>

            <div class="form-group">
                <?= $this->formRow($form->get('dish_name'))?>
                <br>
                <?=$this->formRow($form->get('price'));?>
            </div>

<div class="form-group">
    <?=$this->formSubmit($form->get('submit'));?>
</div>
<?= $this->form()->closeTag()?>
</td>




<td valign="top">
<?php
$form->setName('Main form');
$form->setAttribute('action',$this->url('datagrid',['action'=>'deleteselected']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<table class="table">
    <div>
        <?=$this->formSubmit($form->get('add_new'));?>
        <?=$this->formSubmit($form->get('delete_selected'));?>
    </div>
    <tr>
        <th> </th>
        <th>Dish Name</th>
        <th>Category</th>
        <th>Description</th>
        <th>image source</th>
        <th>price</th>
        <th>options</th>
        <th>&nbsp;</th>
    </tr>

    <?php foreach ($dishes as $dish) : ?>
        <tr>
            <td><input type="checkbox" name="todo_with[]" value="<?=$dish->id?>"></td>
            <td><?= $this->escapeHtml($dish->dish_name) ?></td>
            <td><?= $this->escapeHtml($dish->category) ?></td>
            <td><?= $this->escapeHtml($dish->description) ?></td>
            <td><?= $this->escapeHtml($dish->imageSrc) ?></td>
            <td><?= $this->escapeHtml($dish->price) ?></td>
            <td><?= $this->escapeHtml($dish->options) ?></td>
            <td>
                <a href="<?= $this->url('datagrid', ['action' => 'edit', 'id' => $dish->id]) ?>">Edit</a>
                <a href="<?= $this->url('datagrid', ['action' => 'delete', 'id' => $dish->id]) ?>">Delete</a>
            </td>
        </tr>

    <?php endforeach; ?>
</table>

<?= $this->form()->closeTag()?>
</td></tr></table>
