
<?php

use DataGrid\Forms\IndexForm;

$title = 'Dishes';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form = new IndexForm();

$form->setAttribute('action',$this->url('datagrid',['action'=>'deleteselected']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<table class="table">
    <div>
        <?=$this->formSubmit($form->get('add_new'));?>
        <?=$this->formSubmit($form->get('delete_selected'));?>
    </div>
    <tr>
        <th> </th>
        <th>Dish Name</th>
        <th>Category</th>
        <th>Description</th>
        <th>image source</th>
        <th>price</th>
        <th>options</th>
        <th>&nbsp;</th>
    </tr>

    <?php foreach ($dishes as $dish) : ?>
        <tr>
            <td><input type="checkbox" name="todo_with[]" value="<?=$dish->id?>"></td>
            <td><?= $this->escapeHtml($dish->dish_name) ?></td>
            <td><?= $this->escapeHtml($dish->category) ?></td>
            <td><?= $this->escapeHtml($dish->description) ?></td>
            <td><?= $this->escapeHtml($dish->imageSrc) ?></td>
            <td><?= $this->escapeHtml($dish->price) ?></td>
            <td><?= $this->escapeHtml($dish->options) ?></td>
            <td>
                <a href="<?= $this->url('datagrid', ['action' => 'edit', 'id' => $dish->id]) ?>">Edit</a>
                <a href="<?= $this->url('datagrid', ['action' => 'delete', 'id' => $dish->id]) ?>">Delete</a>
            </td>
        </tr>

    <?php endforeach; ?>
</table>


<?= $this->form()->closeTag()?>
